// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data.EF;

#nullable disable

namespace Project.Migrations.ParserDb
{
    [DbContext(typeof(ParserDbContext))]
    partial class ParserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Project.Areas.Admin.Models.Parser.Discipline", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Coursework")
                        .HasColumnType("longtext");

                    b.Property<string>("Exam")
                        .HasColumnType("longtext");

                    b.Property<string>("Score_mark")
                        .HasColumnType("longtext");

                    b.Property<string>("Score_no_mark")
                        .HasColumnType("longtext");

                    b.Property<int?>("SpecialityId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityId");

                    b.ToTable("Disciplines", (string)null);
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.Parser.Group", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CadetsNumber")
                        .HasColumnType("int");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityId");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.Parser.Semester", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("SelfStudyHours")
                        .HasColumnType("int");

                    b.Property<int?>("StudyHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.ToTable("Semesters", (string)null);
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.Parser.Speciality", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("KursNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Specialities", (string)null);
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.Parser.Discipline", b =>
                {
                    b.HasOne("Project.Areas.Admin.Models.Parser.Speciality", "Speciality")
                        .WithMany("Disciplines")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.Parser.Group", b =>
                {
                    b.HasOne("Project.Areas.Admin.Models.Parser.Speciality", "Speciality")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.Parser.Semester", b =>
                {
                    b.HasOne("Project.Areas.Admin.Models.Parser.Discipline", "Discipline")
                        .WithMany("Semesters")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.Parser.Discipline", b =>
                {
                    b.Navigation("Semesters");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.Parser.Speciality", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
